export const audioData=[
    {
        id: 1,
        title: "Razer Seiren - Micrófono USB",
        price: 150,
        urlImage: "https://tech.com.sv/wp-content/uploads/2021/10/Razer-Seiren-X-4.jpg",
        quantity: 1,
        description: "Micrófono USB para transmisiones: Patrón de pastilla supercardioide preciso, calidad de grabación profesional, construcción ultra compacta, soporte de inclinación resistente",
    },
    {
        id: 2,
        title: "JBL PMB100: Micrófono vocal dinámico",
        price: 150,
        urlImage: "https://m.media-amazon.com/images/I/31Y-w2mFsLL.jpg",
        quantity: 1,
        description: "Micrófono vocal dinámico con cable con cable, negro, JBLPBM100BLKAM",
    },
    {
        id: 3,
        title: "Shure MV7 - Micrófono dinámico USB/XLR",
        price: 150,
        urlImage: "https://www.electronicajaponesa.com/wp-content/uploads/2021/01/MV7-K.jpg",
        quantity: 1,
        description: "Micrófono USB con trípode, para podcasting, grabación, transmisión y juegos, salida de auriculares integrada, micrófono dinámico USB/XLR de metal, tecnología de aislamiento de voz",
    },
    {
        id: 4,
        title: "Blue Yeti USB Mic",
        price: 150,
        urlImage: "https://www.bhphotovideo.com/images/images2000x2000/blue_836213002070_yeti_usb_microphone_black_1103930.jpg",
        quantity: 1,
        description: "USB Mic para grabar y transmitir en PC y Mac, 3 cápsulas de condensador, 4 patrones de captación, salida de auriculares y control de volumen, control de ganancia de micrófono, soporte ajustable, Plug & Play",
    },
    {
        id: 5,
        title: "HyperX SoloCast - Micrófono de condensador USB",
        price: 150,
        urlImage: "https://m.media-amazon.com/images/I/616Iboh1sJL.jpg",
        quantity: 1,
        description: "Micrófono de condensador USB para juegos, para PC, PS4, PS5 y Mac, sensor de toque para silenciar, patrón polar cardioide, ideal para transmisión, podcasts, Twitch, YouTube, Discord",
    },
    {
        id: 6,
        title: "Kit de micrófono USB 192KHZ/24BIT",
        price: 150,
        urlImage: "https://www.zonadigitalsv.com/product/AUA04/image",
        quantity: 1,
        description: "Kit de micrófono USB 192KHZ/24BIT Enchufa y usa MAONO AU-A04 USB para computadora, micrófono cardioide y condensador de podcast micrófono con chipset de sonido profesional para PC Karaoke, YouTube, grabación de juegos",
    },
    {
        id: 7,
        title: "ECOXGEAR EcoTundra - Altavoz inteligente",
        price: 150,
        urlImage: "https://m.media-amazon.com/images/I/81UIV3R8gtL.jpg",
        quantity: 1,
        description: "Altavoz inteligente impermeable flotante portátil Bluetooth inalámbrico de 120 vatios con doble portavasos",
    },
    {
        id: 8,
        title: "JBL Go 3 Eco: Altavoz portátil con Bluetooth",
        price: 150,
        urlImage: "https://img.kytary.com/eshop_es/velky_v2/na/638199156443630000/9ac50935/65095478/jbl-go3-eco-blue.jpg",
        quantity: 1,
        description: "Altavoz portátil con Bluetooth, batería incorporada, función impermeable y a prueba de polvo - azul",
    },
    {
        id: 9,
        title: "Bocina SoundLink Micro de Bose",
        price: 150,
        urlImage: "https://m.media-amazon.com/images/I/61v+-9dV4PL.jpg",
        quantity: 1,
        description: "Bocina SoundLink Micro de Bose con Bluetooth talla única Negro",
    },
    {
        id: 10,
        title: "Soporte de micrófono Samson MK-10",
        price: 150,
        urlImage: "https://m.media-amazon.com/images/I/71+BWrLI5HL.jpg",
        quantity: 1,
        description: "Soporte para micrófono marca Samson MK-10, individual",
    },
]