export const electronicaData = [
    {
        id: 1,
        title: "SanDisk Tarjeta de memoria",
        price: 200,
        urlImage: "https://m.media-amazon.com/images/I/71ltYGbSYlL._AC_SY606_.jpg",
        quantity: 1,
        description: "Tarjeta de memoria Extreme PRO SDXC UHS-I de 128 GB - C10, U3, V30, 4K UHD, tarjeta SD - SDSDXXD-128G-GN4IN",
    },
    {
        id: 2,
        title: "Sensyne Anillo de luz",
        price: 200,
        urlImage: "https://m.media-amazon.com/images/I/61-947b9ZDL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Anillo de luz de 10 pulgadas con trípode extensible de 50 pulgadas, luces LED circulares con soporte para teléfono",
    },
    {
        id: 3,
        title: "Amazon Basics Cable de pantalla DisplayPort a HDMI",
        price: 200,
        urlImage: "https://m.media-amazon.com/images/I/61VeA-UsG0L._AC_SL1500_.jpg",
        quantity: 1,
        description: "Amazon Basics Cable de pantalla DisplayPort a HDMI, unidireccional, 4k@30Hz, 1920x1200, 1080p, conectores chapados en oro, 6 pies, negro",
    },
    {
        id: 4,
        title: "Protector de sobretensión AmazonBasics",
        price: 200,
        urlImage: "https://m.media-amazon.com/images/I/81O5GR2n+xL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Protector de sobretensión AmazonBasics de 6 salidas, 2 unidades, 200 J 2 - unidades Negro",
    },
    {
        id: 5,
        title: "INIU Cargador inalámbrico",
        price: 200,
        urlImage: "https://m.media-amazon.com/images/I/71B+4V5YhnL._AC_SL1251_.jpg",
        quantity: 1,
        description: "INIU Cargador inalámbrico, estación de carga inalámbrica rápida de 15 W con luz adaptable para dormir compatible con iPhone, Samsung, Google Pixel",
    },
    {
        id: 6,
        title: "Bose QuietComfort - Auriculares inalámbricos",
        price: 200,
        urlImage: "https://m.media-amazon.com/images/I/51DOzlkiBTL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Bose QuietComfort - Auriculares inalámbricos con cancelación de ruido, auriculares Bluetooth con audio espacial y cancelación de ruido de clase mundial, color negro",
    },
    {
        id: 7,
        title: "Auriculares estéreo Sony MDRZX110",
        price: 200,
        urlImage: "https://m.media-amazon.com/images/I/41CiQ7hR31L._AC_SL1000_.jpg",
        quantity: 1,
        description: "Auriculares estéreo Sony MDRZX110 Sin micrófono Negro",
    },
    {
        id: 8,
        title: "Sony WH-CH520 - Auriculares inalámbricos",
        price: 200,
        urlImage: "https://m.media-amazon.com/images/I/41lArSiD5hL._AC_SL1200_.jpg",
        quantity: 1,
        description: "Sony WH-CH520 - Auriculares inalámbricos Bluetooth con micrófono, color negro",
    },
    {
        id: 9,
        title: "SAMSUNG Galaxy Buds 2 Pro Auriculares Bluetooth",
        price: 200,
        urlImage: "https://m.media-amazon.com/images/I/51146mqL2nL._AC_SL1500_.jpg",
        quantity: 1,
        description: "SAMSUNG Galaxy Buds 2 Pro Auriculares Bluetooth inalámbricos con cancelación de ruido, sonido de alta fidelidad, audio 360",
    },
    {
        id: 10,
        title: "Amazon Basics Auriculares",
        price: 200,
        urlImage: "https://m.media-amazon.com/images/I/51Le9g6qjRL._AC_SL1336_.jpg",
        quantity: 1,
        description: "Amazon Basics Auriculares intrauditivos con cable, auriculares con micrófono sin tecnología inalámbrica, 0.96 x 0.56 x 0.64 pulgadas, color negro",
    },
]