export const electrodomesticoData = [
    {
        id: 1,
        title: "Betty Crocker Pizzera",
        price: 250,
        urlImage: "https://m.media-amazon.com/images/I/71PRGJV4jbL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Betty Crocker Pizzera para encimera, máquina para hacer pizza de 1440 vatios para el hogar, BC-2958CR",
    },
    {
        id: 2,
        title: "Hamilton Beach (72850)",
        price: 250,
        urlImage: "https://m.media-amazon.com/images/I/61BtxhTS8ZL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Hamilton Beach (72850) - Mini cortador de alimentos, 3 tazas, eléctrico, color negro",
    },
    {
        id: 3,
        title: "Dash Mini Maker",
        price: 250,
        urlImage: "https://m.media-amazon.com/images/I/611K6+mp9CL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Dash Mini Maker - Parrilla, Rosado",
    },
    {
        id: 4,
        title: "BELLA - Vaporizador de alimentos de dos niveles",
        price: 250,
        urlImage: "https://m.media-amazon.com/images/I/81EMHnWPFJL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Vaporizador de alimentos de dos niveles, saludable y rápida cocción simultánea, canastas apilables para verduras o carnes, bandeja de arroz/granos",
    },
    {
        id: 5,
        title: "Elite Gourmet EGR2722A - Parrilla eléctrica",
        price: 250,
        urlImage: "https://m.media-amazon.com/images/I/71cIwZ3dJvL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Elite Gourmet EGR2722A - Parrilla eléctrica de 10.5 x 8.5 pulgadas, mango de tacto frío superficie antiadherente, termostato extraíble/ajustable",
    },
    {
        id: 6,
        title: "GreenLife Estación de desayuno 3 en 1",
        price: 250,
        urlImage: "https://m.media-amazon.com/images/I/517heR1LfRL._AC_SL1200_.jpg",
        quantity: 1,
        description: "GreenLife Estación de desayuno 3 en 1, plancha doble antiadherente de cerámica saludable para huevos, carne, salchicha, tocino, panqueques y sándwiches de desayuno, etc",
    },
    {
        id: 7,
        title: "Presto 07061 - Plancha eléctrica",
        price: 250,
        urlImage: "https://m.media-amazon.com/images/I/61hqjITqd5L._AC_SL1500_.jpg",
        quantity: 1,
        description: "Presto 07061 - Plancha eléctrica con asas extraíbles, 22 pulgadas, 22 - pulgadas",
    },
    {
        id: 8,
        title: "Holstein Housewares - Máquina antiadherente",
        price: 250,
        urlImage: "https://m.media-amazon.com/images/I/617JFoP0n7L._AC_SL1200_.jpg",
        quantity: 1,
        description: "Holstein Housewares - Máquina antiadherente para hacer tortillas y frittatas, negra/acero inoxidable",
    },
    {
        id: 9,
        title: "COSORI Olla a presión eléctrica",
        price: 250,
        urlImage: "https://m.media-amazon.com/images/I/71q-GYnJW9L._AC_SL1500_.jpg",
        quantity: 1,
        description: "COSORI Olla a presión eléctrica de 6 cuartos de galón, olla múltiple instantánea 9 en 1, 13 presets, olla de salteado lento de arroz, al vacío",
    },
    {
        id: 10,
        title: "Hamilton Beach Cafetera Brewer",
        price: 250,
        urlImage: "https://m.media-amazon.com/images/I/71Pw3Ac8+VL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Hamilton Beach Cafetera Brewer de 2 vías, olla de un solo servicio y 12 tazas, acero inoxidable (49980A), jarra",
    },
]