export const muebleData = [
    {
        id: 1,
        title: "SONGMICS - Banco otomano de almacenamiento",
        price: 300,
        urlImage: "https://m.media-amazon.com/images/I/81yAea765YL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Banco otomano de almacenamiento, baúl con tapa, asiento plegable, para dormitorio, pasillo, ahorro de espacio, capacidad de 17.6 galones, soporta hasta 660 libras",
    },
    {
        id: 2,
        title: "VASAGLE UHSR040B05 Perchero de pasillo",
        price: 300,
        urlImage: "https://m.media-amazon.com/images/I/71WPWvWk2WL._AC_SL1500_.jpg",
        quantity: 1,
        description: "VASAGLE UHSR040B05 Perchero de pasillo con banco de zapatos para entrada, muebles de acento industrial con montura de acero, diseño 3 en 1, fácil montaje, marrón miel y negro",
    },
    {
        id: 3,
        title: "IDEALHOUSE Soporte de TV",
        price: 300,
        urlImage: "https://m.media-amazon.com/images/I/61wdXEjQbXL._AC_SL1001_.jpg",
        quantity: 1,
        description: "IDEALHOUSE Soporte de TV Centro de Entretenimiento Industrial, Gris Rústico",
    },
    {
        id: 4,
        title: "AZL1 Life Concept 8 cajones",
        price: 300,
        urlImage: "https://m.media-amazon.com/images/I/81KvPOthGwL._AC_SL1500_.jpg",
        quantity: 1,
        description: "AZL1 Life Concept 8 cajones, dormitorio, cómoda de tela ancha para almacenamiento y organización, color gris",
    },
    {
        id: 5,
        title: "Cómoda con 3 cajones",
        price: 300,
        urlImage: "https://m.media-amazon.com/images/I/61lBRgscqwL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Cómoda con 3 cajones Storkcraft Crescent",
    },
    {
        id: 6,
        title: "Storkcraft Deslizador de aro y otomana de alta calidad",
        price: 300,
        urlImage: "https://m.media-amazon.com/images/I/71Sx8jN8pPL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Storkcraft Deslizador de aro y otomana de alta calidad (natural/beige) – Cojines acolchados con bolsillo de almacenamiento, movimiento mecedor suave, fácil de montar, base de madera maciza",
    },
    {
        id: 7,
        title: "Furinno Luder - Estantería para libros",
        price: 300,
        urlImage: "https://m.media-amazon.com/images/I/61joHwAzbtL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Furinno Luder - Estantería para libros, 5 cubos, color blanco y verde",
    },
    {
        id: 8,
        title: "Furinno Turn'n'Tube - Estantería esquinera",
        price: 300,
        urlImage: "https://m.media-amazon.com/images/I/61s4j2UQNBL._AC_SL1500_.jpg",
        quantity: 1,
        description: "Furinno Turn'n'Tube - Estantería esquinera de 3 niveles multi-propósito",
    },
    {
        id: 9,
        title: "Signature Design by Ashley Neilsville - Mesita de noche",
        price: 300,
        urlImage: "https://m.media-amazon.com/images/I/51iRuj6qbRL._AC_SL1000_.jpg",
        quantity: 1,
        description: "Signature Design by Ashley Neilsville - Mesita de noche industrial con 1 cajón, color marrón claro",
    },
    {
        id: 10,
        title: "VASAGLE Banco de almacenamiento de zapatos",
        price: 300,
        urlImage: "https://m.media-amazon.com/images/I/81-52GzF-HL._AC_SL1500_.jpg",
        quantity: 1,
        description: "VASAGLE Banco de almacenamiento de zapatos de entrada con cojín, 6 compartimentos, estantes ajustables, asiento acolchado, para dormitorio",
    },
]