export const videoData = [
  {
    id: 1,
    title: "WYZE Cam Pan v3",
    price: 100,
    urlImage: "https://global.wyze.com/cdn/shop/products/2pkshadows.jpg?v=1675670162&width=1445",
    quantity: 1,
    description: "Cámara de seguridad inteligente para el hogar con seguimiento de movimiento para bebés y mascotas",
  },
  {
    id: 2,
    title: "Panasonic HC-V180K",
    price: 100,
    urlImage: "https://www.bhphotovideo.com/images/images2500x2500/panasonic_hc_v180k_hc_v160k_full_hd_camcorder_1211809.jpg",
    quantity: 1,
    description: "Videocámara Full HD con zoom óptico de 50x estabilizado",
  },
  {
    id: 3,
    title: "Canon EOS Rebel T7",
    price: 100,
    urlImage: "https://www.rafenlinea.com/94-large_default/camara-canon-eos-rebel-t7.jpg",
    quantity: 1,
    description: "Cámara DSLR con lente de 18-55mm | Wi-Fi integrado | Sensor CMOS de 24.1 MP | Procesador de imagen DIGIC 4+ y videos Full HD",
  },
  {
    id: 4,
    title: "KODAK PIXPRO WPZ2",
    price: 100,
    urlImage: "https://cdn.mercandu.com/ProductVariationImages/b939c60d-8fe1-4f94-b0d9-7ac8c7c801ac.jpg",
    quantity: 1,
    description: "Cámara digital resistente al agua de 16 MP, zoom óptico de 2.7 pulgadas, video LCD Full HD, amarillo",
  },
  {
    id: 5,
    title: "Canon VIXIA HF G70",
    price: 100,
    urlImage: "https://www.rafenlinea.com/99-large_default/camara-de-video-profesional-canon-vixia-hf-g70-.jpg",
    quantity: 1,
    description: "'Videocámara 1/2.3' 4K UHD CMOS Sensor 20x Zoom óptico, Zoom digital 800x, estabilización de imagen, HDMI, transmisión en vivo USB, grabación de pantalla en pantalla",
  },
  {
    id: 6,
    title: "Sony ZV-1F",
    price: 100,
    urlImage: "https://sony.scene7.com/is/image/sonyglobalsolutions/Primary_image-17?$categorypdpnav$&fmt=png-alpha",
    quantity: 1,
    description: "Cámara de Vlog para Creadores de Contenido y Vloggers Negro",
  },
  {
    id: 7,
    title: "Canon Videocámara XA75 Pro",
    price: 100,
    urlImage: "https://cdnx.jumpseller.com/horizontal/image/33376678/resize/1800/1800?1679605380",
    quantity: 1,
    description: "1 pulgada, sensor CMOS 4K UHD, AF CMOS de doble píxel, zoom óptico de 15x, zoom digital 600x, estabilización de imagen, 3G-SDI, HDMI, transmisión en vivo USB",
  },
  {
    id: 8,
    title: "UBeesize Trípode",
    price: 100,
    urlImage: "https://m.media-amazon.com/images/I/61yZqxpjFyL.jpg",
    quantity: 1,
    description: "Trípode extensible de 51 pulgadas con control remoto Bluetooth para iPhone y Android, aluminio resistente, ligero. 2.2 lbs",
  },
  {
    id: 9,
    title: "Joby GorillaPod SLR Zoom Trípode",
    price: 100,
    urlImage: "https://m.media-amazon.com/images/I/51YVJtmxGAL.jpg",
    quantity: 1,
    description: "Las uniones flexibles del trípode GorillaPod pueden doblarse y girar 360°, ofreciendo posibilidades infinitas de posicionamiento para tu cámara profesional incluyendo un lente liviano",
  },
  {
    id: 10,
    title: "GEEKOTO Trípode de cámara",
    price: 100,
    urlImage: "https://m.media-amazon.com/images/I/61w3XA-YGqL.jpg",
    quantity: 1,
    description: "Trípode compacto, cabeza de bola de 360 grados, 17.6 lbs",
  },
];
